// File generated by FlutterFire CLI & configured for Gantt Flow.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyyi0jHHUbW1h-5IMawIwEPNPrdB6XoiQ',
    appId: '1:930996562736:web:ad20355f06b20f6efc36f5',
    messagingSenderId: '930996562736',
    projectId: 'gantt-flow-7ca89',
    authDomain: 'gantt-flow-7ca89.firebaseapp.com',
    storageBucket: 'gantt-flow-7ca89.firebasestorage.app',
    measurementId: 'G-PE40VTPQJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvQQyiicUc5Usr7Lg-EMEB6aNGQPbHTi0',
    appId: '1:930996562736:android:bc2135855c1b816cfc36f5',
    messagingSenderId: '930996562736',
    projectId: 'gantt-flow-7ca89',
    storageBucket: 'gantt-flow-7ca89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs0isOUX-WNzavMxwWVPEhKLD87xcNuJA',
    appId: '1:930996562736:ios:3b39cfe345174010fc36f5',
    messagingSenderId: '930996562736',
    projectId: 'gantt-flow-7ca89',
    storageBucket: 'gantt-flow-7ca89.firebasestorage.app',
    iosBundleId: 'com.cdts.ganttMobile',
  );
}
